import React from 'react';

interface AboutModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const AboutModal: React.FC<AboutModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose}></div>
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] overflow-y-auto p-8 animate-fade-in-up">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-slate-900">About PinoyAppraiser</h2>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-full transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        
        <div className="space-y-6 text-slate-600 leading-relaxed">
          <div className="inline-flex items-center px-3 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold uppercase tracking-wide mb-2">
            Beta Release v1.0
          </div>

          <p>
            Welcome to PinoyAppraiser. This website is a test platform currently undergoing daily changes and optimizations to improve its accuracy and features.
          </p>

          <p>
            This project is headed and supervised by a <strong>PRC Licensed Real Estate Appraiser</strong> to ensure that the logic and parameters used generally align with standard valuation principles.
          </p>
          
          <p>
            However, please be aware that we do not claim perfection. The data generated by this site is powered by AI and should be considered as <strong>initial findings</strong> or rough estimates only.
          </p>

          <div className="bg-slate-50 border-l-4 border-slate-900 p-6 rounded-r-lg mt-4">
            <p className="text-slate-900 font-bold text-lg leading-relaxed">
              For official purposes and to ensure accuracy, getting the services of a PRC Licensed Real Estate Appraiser in the Philippines is highly recommended for better results.
            </p>
          </div>
        </div>

        <div className="mt-8 pt-6 border-t border-slate-100 flex justify-end">
          <button 
            onClick={onClose}
            className="bg-slate-900 text-white px-6 py-2.5 rounded-lg font-medium hover:bg-slate-800 transition-colors shadow-lg shadow-slate-500/20"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};